apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-seller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-seller
  template:
    metadata:
      labels:
        app: server-seller
    spec:
      containers:
        - name: server-seller
          image: gcr.io/YOUR_PROJECT_ID/server-seller:latest
          ports:
            - containerPort: 6004
          command:
            [
              "python3",
              "server_seller/server.py",
              "--host",
              "0.0.0.0",
              "--port",
              "6004",
              "--customer-host",
              "db-customer",
              "--customer-port",
              "6001",
              "--product-host",
              "db-product",
              "--product-port",
              "6002",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: server-seller
spec:
  selector:
    app: server-seller
  ports:
    - port: 6004
      targetPort: 6004
