apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-buyer
  template:
    metadata:
      labels:
        app: server-buyer
    spec:
      containers:
        - name: server-buyer
          image: gcr.io/YOUR_PROJECT_ID/server-buyer:latest
          ports:
            - containerPort: 6003
          command:
            [
              "python3",
              "server_buyer/buyer_server.py",
              "--host",
              "0.0.0.0",
              "--port",
              "6003",
              "--customer-host",
              "db-customer",
              "--customer-port",
              "6001",
              "--product-host",
              "db-product",
              "--product-port",
              "6002",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: server-buyer
spec:
  selector:
    app: server-buyer
  ports:
    - port: 6003
      targetPort: 6003
